name: weltweit
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  json_annotation: any
  freezed_annotation: any

  # Network
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  connectivity_plus: ^3.0.2

  # DI
  get_it: ^7.2.0
  equatable: ^2.0.5

  # Local
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.0.15

  geocoding: ^2.1.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1

  #UI
  flutter_staggered_animations: ^1.1.1 # #animation
  easy_localization: ^3.0.1 # localization
  awesome_dialog: ^3.0.2 #dialog
  flutter_svg: ^1.1.6 #svg images
  cached_network_image: ^3.2.2
  flutter_spinkit: ^5.1.0 #loading
  pin_code_fields: ^7.4.0
  webview_flutter: ^3.0.4
  country_code_picker: ^2.0.2
  file_picker: ^5.2.2
  stylish_bottom_bar: ^0.1.5
  smooth_page_indicator: ^1.0.0+2
  flutter_timer_countdown: ^1.0.5
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.6

  #share:
  share_plus: ^6.3.0

  #firebase
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1
  # firebase_crashlytics: ^3.0.2
  # firebase_database: ^10.0.10
  # firebase_dynamic_links: ^5.0.11
  #  firebase_dynamic_links: ^4.0.0
  flutter_local_notifications: ^9.5.3+1

  # State management
  permission_handler: ^10.2.0
  flutter_bloc: ^8.1.1
  #log
  logger: ^1.1.0
  logging: ^1.1.0
  multi_select_flutter: ^4.1.3
  im_stepper: ^1.0.1+1

  #fireweltweit
  # fireweltweit_core: ^2.3.0
  # fireweltweit_messaging: ^14.1.1
  #  fireweltweit_crashlytics: ^3.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  material_dialogs: ^1.1.4
  persistent_bottom_nav_bar: ^5.0.2
  loading_animation_widget: ^1.2.0+4
  animated_snack_bar: ^0.3.0
  image_picker: ^0.8.7
  location: ^4.4.0
  photo_view: ^0.14.0
  video_player: ^2.6.1
  flutter_launcher_icons: ^0.12.0
  flutter_animate: ^4.1.1+1
  font_awesome_flutter: ^10.4.0 
  awesome_extensions: ^2.0.7
  full_screen_image: ^2.0.0
  sentry_flutter: ^7.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  build_runner: any
  freezed: any
  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/services/images/logo.jpg"
# flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/strings/
    - assets/images/gif/
    - assets/images/svg/
    - lib/presentation/component/inputs/phone_country/flags/

  fonts:
    - family: MontserratArabic
      fonts:
        - asset: assets/fonts/montserratArabicBlack.otf
          weight: 900
        - asset: assets/fonts/montserratArabicExtraBold.otf
          weight: 800
        - asset: assets/fonts/montserratArabicBold.otf
          weight: 700
        - asset: assets/fonts/montserratArabicSemiBold.otf
          weight: 600
        - asset: assets/fonts/montserratArabicMedium.otf
          weight: 500
        - asset: assets/fonts/montserratArabicRegular.otf
          weight: 400
        - asset: assets/fonts/montserratArabicLight.otf
          weight: 300
        - asset: assets/fonts/montserratArabicExtraLight.otf
          weight: 200
        - asset: assets/fonts/montserratArabicThin.otf
          weight: 100