// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf7ligRrobz7TzJZ4QacoPdPwEeO8L2MA',
    appId: '1:377126115910:android:ba7850892db8e63cd30847',
    messagingSenderId: '377126115910',
    projectId: 'done-8e8c2',
    databaseURL: 'https://done-8e8c2-default-rtdb.firebaseio.com',
    storageBucket: 'done-8e8c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa_EdtcUlj7Z118tgWjiU8sa9uKKNhTlk',
    appId: '1:377126115910:ios:3e05e3b79e1cc846d30847',
    messagingSenderId: '377126115910',
    projectId: 'done-8e8c2',
    databaseURL: 'https://done-8e8c2-default-rtdb.firebaseio.com',
    storageBucket: 'done-8e8c2.appspot.com',
    iosClientId: '377126115910-35in3njj87i2ct36ppbm1esg3fvvf9eg.apps.googleusercontent.com',
    iosBundleId: 'com.matrixclouds.done',
  );
}
