# Uncomment this line to define a global platform for your project
 platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}


def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), _FILE_)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  flutter_install_all_ios_pods File.dirname(File.realpath(_FILE_))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
       target.build_configurations.each do |config|
              # You can remove unused permissions here
              # for more information: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
              # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
                '$(inherited)',

                ## dart: PermissionGroup.camera
                'PERMISSION_CAMERA=1',

                ## dart: PermissionGroup.notification
                'PERMISSION_NOTIFICATIONS=1',
                ## dart: PermissionGroup.location
                'PERMISSION_LOCATION=1',

                ## Optionally, you can add these if you need specific location types:
                'PERMISSION_LOCATION_ALWAYS=1', # For always access
                'PERMISSION_LOCATION_WHEN_IN_USE=1', # For access when app is in use

              ]
       end
  end

  # This is to remove arm64 from the available archs:
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings["EXCLUDED_ARCH[sdk=iphonesimulator*]"] = "arm64"

  end
end